ChildCard/apps/accounts/urls.py
from django_registration.backends.activation.views import RegistrationView
from django.contrib.auth.views import PasswordResetView
from django.urls import path, include
from .forms import EmailValidationOnForgotPassword
from .forms import EmailValidationOnRegister

urlpatterns = [
    path('register/', RegistrationView.as_view(form_class=EmailValidationOnRegister),
         name='form_valid'), # Addition check email
    path('', include('django.contrib.auth.urls')),
    path('', include('django_registration.backends.activation.urls')),
    path('sifre-sifirla/', PasswordResetView.as_view(form_class=EmailValidationOnForgotPassword),
         name='password_reset'), # Addition check email
]

ChildCard/apps/main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
    path('setting_account_form/', views.setting_account_form, name="setting_account_form"),
    path('setting_account_complete/', views.setting_account_complete, name="setting_account_complete"),
    path('create_card_form/', views.create_card_form, name="create_card_form"),
    path('create_card_complete/', views.create_card_complete, name="create_card_complete"),
    path('view_card/', views.view_card, name="view_card")
]

ChildCard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('', include('social.apps.django_app.urls', namespace='social')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

ChildCard/apps/accounts/models.py
# from django.contrib.auth.models import User, AbstractUser
# from django.core.mail import send_mail
#
#
# class My_AbstractUser(AbstractUser):
#
#     def email_user(self, subject, message, from_email=None, **kwargs):
#         """Send an email to this user."""
#         send_mail(subject, message, from_email, [self.email], fail_silently=True, **kwargs)
#
#
# class My_User(My_AbstractUser):
#     ...

ChildCard/apps/main/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid


class Card(models.Model):
    global_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    child_name = models.CharField(verbose_name='имя ребёнка', max_length=50)
    BOY = 1
    GIRL = 2
    GENDER_TYPES = (
        (BOY, 'boy'),
        (GIRL, 'girl'),
    )
    gender = models.IntegerField(verbose_name='пол ребёнка', choices=GENDER_TYPES)
    path_child_photo = models.FilePathField(verbose_name='путь к фото', default=None, blank=True, null=True)
    creator_id = models.ForeignKey(User, verbose_name='создатель карточки', on_delete=models.CASCADE)
    date = models.DateTimeField(verbose_name='дата создания', auto_now=True)

    def __str__(self):
        return self.child_name

    class Meta:
        verbose_name = 'Карточка'
        verbose_name_plural = 'Карточки'

ChildCard/apps/accounts/forms.py
from smtplib import SMTPDataError

from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordResetForm
from django.core.mail import send_mail
from django_registration.forms import RegistrationForm
from django_registration import validators

from ChildCard import settings


class EmailValidationOnForgotPassword(PasswordResetForm):

    def clean_email(self):
        email = self.cleaned_data['email']
        if not User.objects.filter(email__iexact=email).exists():
            msg = "Данный адрес электронной почты не зарегистрирован."
            self.add_error('email', msg)
        elif not User.objects.filter(email__iexact=email, is_active=True).exists():
            msg = "Данный адрес электронной почты не активирован."
            self.add_error('email', msg)

        return email


class EmailValidationOnRegister(RegistrationForm):

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email__iexact=email, is_active=True).exists():
            msg = validators.DUPLICATE_EMAIL
            self.add_error('email', msg)
        # settings.EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
        # try:
        #     send_mail('TestValid', '', settings.DEFAULT_FROM_EMAIL, [email])
        # except SMTPDataError:
        #     msg = 'Данный адрес электронной почты не существует'
        #     self.add_error('email', msg)
        # settings.EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
        return email

ChildCard/apps/main/views.py
import os
import io
import ftplib
import json
import requests

from django.shortcuts import render, redirect
from django.conf import settings
from django.contrib.auth.decorators import login_required

from django.utils import timezone

from .models import Card

from PIL import Image

ROOT_STATIC_APP = f'{settings.PROJECT_ROOT}/static'


@login_required
def index(request):
    cards_data = Card.objects.filter(creator_id=request.user)
    indexes = range(len(cards_data))
    return render(request, 'main/index.html', {'cards_data': cards_data,
                                               'indexes': indexes})


@login_required
def create_card_form(request):
    return render(request, 'main/create_card.html')


@login_required
def create_card_complete(request):
    photo_label, photo_format = request.FILES['photo'].name.rsplit('.', 1)
    if photo_format not in ['jpg', 'png']:
        return render(request, 'main/create_card.html')

    child_card = Card(
        child_name=request.POST['childname'],
        gender=int(request.POST['gender']),
        creator_id=request.user
    )
    child_card.save()

    photo_label = f"{photo_label}_{child_card.global_id}"
    photo_name = f"{photo_label}.{photo_format}"

    stream = io.BytesIO(request.FILES['photo'].read())
    photo = Image.open(stream)

    ftp = ftplib.FTP()

    ftp.connect('46.149.233.52', 30)
    ftp.login(os.environ['FTP_USER'], os.environ['FTP_PASSWORD'])
    ftp.cwd('ChildCard_images')

    src_rel = f'main/image/child_photo/user_{request.user.username}'
    src_abs = f'{ROOT_STATIC_APP}/{src_rel}'

    if f'user_{request.user.username}' not in os.listdir(f'{ROOT_STATIC_APP}/main/image/child_photo'):
        os.mkdir(src_abs)
    if f'user_{request.user.username}' not in ftp.nlst():
        ftp.mkd(f'user_{request.user.username}')
    ftp.cwd(f'user_{request.user.username}')

    photo = photo.resize((1200, 800))
    photo.save(f'{src_abs}/{photo_name}')

    ftp.storbinary(cmd=f"STOR {photo_name}", fp=open(f'{src_abs}/{photo_name}','rb'))

    ftp.close()

    child_card.path_child_photo = f"{src_rel}/{photo_name}"
    child_card.save()

    requests.post(url='https://lmfl1ie4pj.execute-api.us-east-1.amazonaws.com/api_sns/admin',
                  data=json.dumps({'Message': f"User {request.user.username} created card '{child_card.child_name}'"}))

    return redirect(request.POST['next'], request)


@login_required
def setting_account_form(request):
    cards = Card.objects.filter(creator_id=request.user)
    return render(request, 'main/setting_account.html', {'cards': cards})


def delete_card(card_id):
    card = Card.objects.get(global_id=card_id)
    card_name = card.child_name
    src_abs = f'{ROOT_STATIC_APP}/{card.path_child_photo}'
    os.remove(src_abs)

    _, username, photo_name = card.path_child_photo.rsplit('/', 2)

    ftp = ftplib.FTP()

    ftp.connect('46.149.233.52', 30)
    ftp.login(os.environ['FTP_USER'], os.environ['FTP_PASSWORD'])
    ftp.cwd('ChildCard_images')
    ftp.cwd(username)
    ftp.delete(photo_name)

    card.delete()

    return card_name


@login_required
def setting_account_complete(request):
    user = request.user
    user.first_name = request.POST['first_name']
    user.last_name = request.POST['last_name']
    user.save()

    cards_id = request.POST.getlist('cards[]')
    cards = ""
    for card_id in cards_id:
        card_name = delete_card(card_id)
        cards += f" '{card_name}',"

    requests.post(url='https://lmfl1ie4pj.execute-api.us-east-1.amazonaws.com/api_sns/admin',
                  data=json.dumps({'Message': f"User {request.user.username} deleted cards [{cards[:-1]} ]"}))
    return redirect(request.POST['next'], request)


@login_required
def view_card(request):
    card = Card.objects.get(global_id=request.GET['card_id'])
    boy, girl = Card.BOY, Card.GIRL
    return render(request, 'main/view_card.html', {'card': card,
                                                   'boy': boy,
                                                   'girl': girl})


@login_required
def about(request):
    return render(request, 'main/about.html')


@login_required
def contact(request):
    return render(request, 'main/contact.html')

ChildCard/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
{#    <meta http-equiv="refresh" content="5;{% url 'main:index' %}">#}
    <title>{% block title %}ChildCard{% endblock %}</title>
    {% load staticfiles %}
    <script src="{% static 'download/js/fontawesome-b8cb5fa048.js' %}"></script>
    <script src="{% static 'download/js/jquery-latest.min.js' %}"></script>
    <script src="{% static 'download/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'download/js/jquery-3.4.1.min.js' %}"></script>

    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'download/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/menu.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/accountMenu.css' %}" type="text/css">
    {% block styles %}{% endblock %}
    <style>
        @media (min-width: 1100px) {
            .jumbotron
            {
                background: url({% static 'main/image/back_image1.jpg' %}) no-repeat center center fixed;
                -webkit-background-size: cover;
                -moz-background-size: cover;
                -o-background-size: cover;
                background-size: cover;
            }
        }
        @media (max-width: 1100px) {
            .jumbotron
            {
                background: linear-gradient(to bottom, #ace6ee, #6fdf50);
                {#background: url({% static 'main/image/back_image2.jpg' %}) no-repeat center center fixed;#}
                {#-webkit-background-size: cover;#}
                {#-moz-background-size: cover;#}
                {#-o-background-size: cover;#}
                {#background-size: cover;#}
            }
        }
    </style>
</head>
<body>
    
    <section class="header">
        <span id="logo"><a href="{% url 'main:index' %}">ChildCard</a></span>
        <span id="menu">
            <ul class="menu-main">
                  <li><a id="li_main" href="{% url 'main:index' %}" class="current">Главная</a></li>
                  <li><a id="li_about" href="{% url 'main:about' %}">О НАС</a></li>
                  <li><a id="li_contact" href="{% url 'main:contact' %}">Контакты</a></li>
            </ul>
        </span>

        <span id="account">
          <ul class="topmenu">
            <li class="submenu-link">
              <span>
                  {% if user.first_name != "" and user.last_name != "" %}
                    {{ user.first_name }} {{ user.last_name|first }}.
                  {% else %}
                    {{ user.username }}
                  {% endif %}
              </span>
              <ul class="submenu">
                <li><span class="label"><i class="fa fa-user"></i></span><a href="{% url 'main:setting_account_form' %}">Настройки</a></li>
                <li><span class="label"><i class="fa fa-sign-out"></i></span><a href="{% url 'logout'%}?next={{request.path}}">Выйти</a></li>
              </ul>
            </li>
          </ul>
        </span>
    </section>
    <section  class="jumbotron">
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </section >
    <section class="footer">
        &copy; Все права защищены 2019
        <span><b>GitHub:</b> <a href="https://github.com/Dima12101/ChildCard">https://github.com/Dima12101/ChildCard</a></span>
    </section >
</body>
</html>

ChildCard/templates/base_auth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Вход в ChildCard{% endblock %}</title>
    {% load staticfiles %}
    <script src="{% static 'download/js/fontawesome-b8cb5fa048.js' %}"></script>
    
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'download/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'auth/css/main.css' %}" type="text/css">
    {% block styles %}{% endblock %}
    <style>
        @media (min-width: 1100px) {
            .jumbotron
            {
                background: url({% static 'auth/image/back_image.jpg' %}) no-repeat center center fixed;
                -webkit-background-size: cover;
                -moz-background-size: cover;
                -o-background-size: cover;
                background-size: cover;
            }
        }
        @media (max-width: 1100px) {
            .jumbotron
            {
                background: linear-gradient(10deg, #aceeeb, #f6ffff);
            }
        }
    </style>
</head>
<body>
    <section  class="jumbotron">
        <div class="container content">
            {% block content %}{% endblock %}
        </div>
    </section >
    <section class="footer">
        &copy; Все права защищены 2019
        <span><b>GitHub:</b> <a href="https://github.com/Dima12101/ChildCard">https://github.com/Dima12101/ChildCard</a></span>
    </section >
</body>
</html>

ChildCard/templates/django_registration/activation_complete.html
{% extends "base_auth.html" %}
{% block content %}
<div class="auth-block success-result">
    <h1>Аккаунт активирован</h1>
    <p>
        <a href="{% url 'login'%}">Войти</a> на сайт?
    </p>
</div>
{% endblock %}

ChildCard/templates/django_registration/activation_failed.html
{% extends "base_auth.html" %}
{% block title %}Ошибка активации{% endblock %}

{% block content %}
    <div class="auth-block error-block">
            <h1>Ошибка активации аккаунта</h1>
            <p>
                Ссылка на активацию аккаунта не валидна.
                <br />
                Скорей всего она была уже использована.
            </p>
            <p>
                По всем вопросам обращаться по следующему адресу:
                <a href="mailto:child-card@mail.ru" target="display"> child-card@mail.ru </a>
            </p>
    </div>
{% endblock %}

ChildCard/templates/django_registration/registration_complete.html
{% extends "base_auth.html"  %}
{% block title %}Регистрация{% endblock %}
{% block content %}
<div class="auth-block success-result">
    <h1>Регистрация завершена</h1>
    <p>
        Спасибо за уделённое время. На ваш e-mail отправлен
        код подтверждения.
    </p>
    <p>
        <i>Необходимо подтвердить регистрацию,
            просто кликнув по указанной ссылке</i>
    </p>
</div>
{% endblock %}

ChildCard/templates/django_registration/registration_form.html
{% extends "base_auth.html" %}
{% block title %}Регистрация{% endblock %}
{% load staticfiles %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'auth/css/register.css' %}" type="text/css">
{% endblock %}
{% block content %}
<div class="auth-block">
    <h1>Регистрация</h1>
    <form method="post" action="">
        {% csrf_token %}
        <div class="form-group required" id="div_id_username">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-user ti-user"></i></span>
                <input id="id_username" required name="username" type="text" class="form-control" maxlength="150"
                       placeholder="Ваш логин" autofocus>
            </div>
            <small id="hint_id_username" class="form-text text-muted">
                    Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_.
            </small>
            {% if form.username.errors %}{{ form.username.errors }}{% endif %}
        </div>
        <div class="form-group required" id="div_id_email">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                <input id="id_email" name="email"  class="emailinput form-control" required maxlength="254"
                       placeholder="Ваш email">
            </div>
            {% if form.email.errors %}{{ form.email.errors }}{% endif %}
        </div>
        <div class="form-group required" id="div_id_password1">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-key"></i></span>
                <input name="password1" type="password" class="textInput form-control" required id="id_password1"
                               placeholder="Новый пароль">
            </div>
            <small id="hint_id_password1" class="form-text text-muted">
                <ul>
                    <li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li>
                    <li>Ваш пароль должен содержать как минимум 8 символов.</li>
                    <li>Ваш пароль не может быть одним из широко распространённых паролей.</li>
                    <li>Ваш пароль не может состоять только из цифр.</li>
                </ul>
            </small>
        </div>
        <div class="form-group required" id="div_id_password2">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-key"></i></span>
                <input name="password2" type="password" class="textInput form-control" required id="id_password2"
                               placeholder="Подтверждение нового пароля">
            </div>
            <small id="hint_id_password2" class="form-text text-muted">
                Для подтверждения введите, пожалуйста, пароль ещё раз.
            </small>
            {% if form.password1.errors %}{{ form.password1.errors }}{% endif %}
            {% if form.password2.errors %}{{ form.password2.errors }}{% endif %}
        </div>
        {% if form.non_field_errors %}{{ form.non_field_errors }}{% endif %}
        <input type="hidden" name="next" value="{{ next }}">
        <button class="btn btn-primary btn-block" type="submit">ЗАРЕГИСТРИРОВАТЬСЯ</button>
    </form>
</div>
{% endblock %}

ChildCard/templates/main/about.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'main/css/info.css' %}" type="text/css">
{% endblock %}
{% block content %}

	<div class="info-block">
    	<h1>О НАС</h1>
        <div id="content-scroll">
            <h4>Проблема</h4>
        	<p>
    	        Многие родители следят за развитием и состоянием своего ребёнка, фиксируя различную информацию о нём. Хранение обычно происходит в каких-либо тетрадках, альбомах и т.д. Помимо этого часто возникает у них вопрос, как интерпретировать собранную информацию. Частым решением является: различные интернет ресурсы и форумы.
            </p>
            <p>
                К примеру:
                <br/>
                <i>
                    Допустим есть информация о росте ребёнка в определённый его возраст. Возникает вопрос: всё ли хорошо и что стоит ожидать в будущем.
                    <p>
                        Что обычно делают:
                        <ul>
                            <li>Либо задают вопрос на форуме <-Тут обычно очень субъективная информация.</li>
                            <li>Либо пользуются специальными центильными таблицами ВОС <-Не все про них знают и не все в них разбираются</li>
                        </ul>
                    </p>
                </i>
    	    </p>
            <h4>Что сервис предлагает</h4>
            <p>
                Создание карточки/паспорта ребёнка, в которой есть возможность вносить различную информацию на определённый возраст ребёнка:
                <ul>
                    <li><i>Рост, вес, окружность груди и головы</i> -> На основе этой информации вы получаете текущие состояние ребёнка. А также можете посмотреть различные графики анализа темпов развития.</li>
                    <li><i>Фото</i> -> визуальное развитие ребёнка</li>
                    <li><i>Заболевания, прививки</i> -> просто знать, что они были</li>
                </ul>
            </p>
        </div>
	</div>


    <script>
        $("#li_main").removeClass("current");
        $("#li_contact").removeClass("current");
        $("#li_info").addClass("current");
    </script>
{% endblock %}

ChildCard/templates/main/contact.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'main/css/info.css' %}" type="text/css">
{% endblock %}
{% block content %}

	<div class="info-block">
    	<h1>КОНТАКТЫ</h1>
        <p>
            Студент <i>Санкт-Петербургского государственного университета</i> факультета <i>"Прикладная математика и процессы управления"</i> направления <i>"Программирование и информационные технологии"</i>.
            <br/>
            Со мной можно связаться в следующих соц.сетях:
            <ul>
                <li><i>Вконтакте</i>: id134759185</li>
                <li><i>Телеграм</i>: @Dima12101</li>
            </ul>
        </p>
	</div>


    <script>
        $("#li_main").removeClass("current");
        $("#li_contact").removeClass("current");
        $("#li_info").addClass("current");
    </script>
{% endblock %}

ChildCard/templates/main/create_card.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'main/css/create_card.css' %}" type="text/css">
{% endblock %}
{% block content %}
    <div class="create-block">
    <h1>Создание карточки</h1>
    <form method="post" action="{% url 'main:create_card_complete' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group" id="div_id_childname">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-child"></i></span>
                <input id="id_childname" required name="childname" type="text" class="form-control" placeholder="Имя ребёнка">
            </div>
        </div>
        <div class="form-group" id="div_id_gender">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-venus-mars"></i></span>
                <input id="id_gender_boy"  name="gender" type="radio" value="1">
                <label for="id_gender_boy">Мальчик</label>
                <input id="id_gender_girl"  name="gender" type="radio" value="2">
                <label for="id_gender_girl">Девочка</label>
            </div>
        </div>
        <div class="form-group" id="div_id_photo">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-file-image-o"></i></span>
                <input id="id_photo" required name="photo" type="file" class="form-control" accept="image/*">
            </div>
        </div>
        <div>
        <img id="photo-preview" src="{% static 'main/image/default_image.jpg' %}" />
            <br />
            <a href="#" id="reset-photo-preview">удалить изображения</a>
        </div>

        {% if form.errors %}
            {{ form.childname.errors }}
            {{ form.photo.errors }}
            {{ form.non_field_errors  }}
        {% endif %}

        <input type="hidden" name="next" value="{% url 'main:index' %}">
        <button class="btn btn-primary btn-block" type="submit">СОЗДАТЬ</button>
    </form>
</div>

<script type = "text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script>
    $('#id_photo').change(function () {
        var input = $(this)[0];
        if (input.files && input.files[0]) {
            if (input.files[0].type.match('image.*')) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#photo-preview').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            } else {
                console.log('ошибка, не изображение');
            }
        } else {
            console.log('хьюстон у нас проблема');
        }
    });

    $('#reset-photo-preview').click(function() {
        $('#id_photo').val('');
        $('#photo-preview').attr('src', '{% static 'main/image/default_image.jpg' %}');
    });
</script>

<style>
#photo-preview{
    width: 300px;
    height: 200px;
}

#reset-photo-preview, #reset-photo-preview:active {
    text-decoration: none;
    color: #24727b;
}
#reset-photo-preview:focus, #reset-photo-preview:hover{
    color: #2c959e;
}
</style>
{% endblock %}

ChildCard/templates/main/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="container cards">
        <div class="row">
            <div class="col text-center text-uppercase">
                <div class="title">
                    <h4><span>Карточки</span></h4>
                </div>
            </div>
        </div>
        {% if cards_data.count != 0 %}
            <div id="carousel" class="carousel slide mw-100" data-ride="carousel">
                <a id="add_card" href="{% url 'main:create_card_form' %}"><i class="fa fa-plus-circle" aria-hidden="true"></i></a>
                <div class="carousel-inner">
                    {% for card_data in  cards_data%}
                        <div class="carousel-item">
                            <a href="{% url 'main:view_card' %}?card_id={{ card_data.global_id }}"><img class="img-fluid photo" src="{% static card_data.path_child_photo %}" alt="photo"></a>
                            <div class="carousel-caption">
                                <h3>{{card_data.child_name}}</h3>
                            </div>
                        </div>
                    {% endfor %}
                    {% if cards_data.count != 1 %}
                        <!-- Элементы управления -->
                        <a class="fa fa-arrow-circle-left carousel-control-prev" href="#carousel" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Предыдущий</span>
                        </a>
                        <a class="fa fa-arrow-circle-right carousel-control-next" href="#carousel" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Следующий</span>
                        </a>
                    {% endif %}
                </div>
                <!-- Индикаторы -->
                <ol class="carousel-indicators">
                    {% for i in indexes %}
                        <li data-target="#carousel" data-slide-to="{{i}}" class="indicators"></li>
                    {% endfor %}
                </ol>
            </div>
        {% else %}
            <div id="bth-create-card">
                <a href="{% url 'main:create_card_form' %}">Создать</a>
            </div>
        {% endif %}
    </div>

    <script>
        $(".carousel-item:first-of-type").addClass("active");
        $(".indicators:first-of-type").addClass("active");
    </script>

{% endblock %}

ChildCard/templates/main/setting_account.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'main/css/settings.css' %}" type="text/css">
{% endblock %}
{% block content %}

	<div class="setting-block">
    	<h1>Настройки аккаунта</h1>
        <div class="content-scroll">
            <form method="post" action="{% url 'main:setting_account_complete' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <span><i class="fa fa-user"></i></span>
                <ul>
                    <li>
                        <div class="form-group" id="div_id_first_name">
                            <div class="input-group">
                                <span class="input-group-addon"></span>
                                <input id="id_first_name" name="first_name" type="text" class="form-control" placeholder="Имя" value="{{ user.first_name }}">
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="form-group" id="div_id_last_name">
                            <div class="input-group">
                                <span class="input-group-addon"></span>
                                <input id="id_last_name" name="last_name" type="text" class="form-control" placeholder="Фамилия" value="{{ user.last_name }}">
                            </div>
                        </div>
                    </li>
                </ul>
                <h5><i class="fa fa-child"></i> (Удалить)</h5>
                {% if cards.count != 0 %}
                    <ul>
                        <li>
                            <div class="form-group" id="div_id_cards">
                                {% for card in cards %}
                                    <div class="div_card">
                                        <input type="checkbox" id="card-{{ card.global_id }}" class="form-control" name="cards[]" value="{{ card.global_id }}">
                                        <label for="card-{{ card.global_id }}"><img src="{% static card.path_child_photo %}" alt="card photo">  Карточка '{{ card.child_name }}'</label>
                                    </div>
                                {% endfor %}
                            </div>
                        </li>
                    </ul>
                {% else %}
                    <div>У вас нет карточек</div>
                {% endif %}

                {% if form.errors %}
                    {{ form.first_name.errors }}
                    {{ form.last_name.errors }}
                    {{ form.non_field_errors  }}
                {% endif %}

                <input type="hidden" name="next" value="{% url 'main:index' %}">
                <button class="btn btn-primary btn-block" type="submit">СОХРАНИТЬ</button>
            </form>
        </div>
	</div>

{% endblock %}